---
- name: common
  hosts: all
  become: yes
  roles:
    - common

- name: craete nfs server
  hosts: server
  become: yes
  roles:
    - nfs

- name: create client machine 
  hosts: client
  become: yes
  vars:
    - nfs_server: "192.168.1.66"
    - nfs_mounts:
        - { src: /mnt/nfs, dest: /mnt/nfs }
  roles:
    - configs
    - nfs

