---
- name: create nginx static file serve
  hosts: client
  become: yes
  vars:
    - is_nfs_server: false
    - nfs_server: "{{ hostvars['server']['ansible_default_ipv4']['address'] }}"
    - nfs_mount:
      - src: /mnt/nfs
      - dest: /mnt/nfs 
  roles:
    - common
    - nfs

- name: config user
  hosts: client
  roles:
    - configs
