---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: fedora1
    box: fedora/32-cloud-base
    memory: 1536
    cpus: 1
  - name: fedora2
    box:  fedora/31-cloud-base
    memory: 1536
    cpus: 1
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
verifier:
  name: ansible
