---
- name: include server
  include: server.yml
  when: is_nfs_server

- name: mount client mounts
  mount: 
    src: "{{ nfs_gerver }}:{{ nfs_mounts.src }}"
    path: "{{ nfs_mounts.dest }}"
    state: present
    fstype: nfs
  loop: "{{ nfs_mounts }}"
  tags: always
