---
- name: include server
  include: server.yml
  when: is_nfs_server

- name: mount client mounts
  mount: 
    src: "{{ nfs_server }}:{{ item.src }}"
    path: "{{ item.dest }}"
    state: mounted
    fstype: nfs
  loop: "{{ nfs_mounts }}"
