---
- name: ensure nfs is installed
  package: name=nfs-utils state=present

- name: nfs config file
  template: src=nfs_expose.j2 dest=/etc/exports mode=0644 owner=root group=root
  notify: restart nfs config

- name: enable nfs
  service: name=nfs-server state=started enabled=yes

- name: Ensure directories to export exist
  file: 
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"
