---
- name: ensure vim is installed
  package: name=vim state=present
  become: yes

- name: add vim cach dir
  file: path="{{ ansible_env.HOME }}/.vim/cache" state=directory mode=0733

- name: add vim undo dir
  file: path="{{ ansible_env.HOME }}/.vim/undo" state=directory mode=0733

- name: add config file
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0700

- name: install git
  package: name=git state=present
  become: yes

- name: ensure dir .ssh exzist
  file: path="{{ ansible_env.HOME }}/.ssh" state=directory mode=0700

- name: copy ssh file
  template:
    src: ssh_key
    dest: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    mode: 0700

- name: enable sshd
  service: name=sshd state=started enabled=yes
  become: yes

- name: enable root without password
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ ansible_env.USER }}
    mode: "731"
  become: yes
