---
- name: ensure selinux control packages
  package: name=libselinux-python3 state=installed

- name: ensure selinux status
  selinux: state={{ selinux_state }} policy={{ selinux_policy }}
  register: result

- name: change if needed
  debug: msg="test"
  notify: reboot
  changed_when: true
  when: result.reboot_required
