---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: fedora-cloud
    box: fedora/32-cloud-base
    memory: 1536
    cpus: 1
  - name: rhel8
    box: generic/rhel8
    memory: 1536
    cpus: 1
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
verifier:
  name: ansible
