---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: fedora
    box:  fedora/34-cloud-base
    memory: 1536
    cpus: 1
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
verifier:
  name: ansible
